MySociety.Web/Controllers/MyProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MySociety.Entity.ViewModels;
using MySociety.Service.Common;
using MySociety.Service.Interfaces;

namespace MySociety.Web.Controllers;

[Authorize]
public class MyProfileController : Controller
{
    private readonly IUserService _userService;
    private readonly IVehicleService _vehicleService;
    private readonly IProfileService _profileService;

    public MyProfileController(IUserService userService, IVehicleService vehicleService, IProfileService profileService)
    {
        _userService = userService;
        _vehicleService = vehicleService;
        _profileService = profileService;
    }

    /*------------------------------------------------------ View My Profile and Update Profile---------------------------------------------------------------------------------
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        ProfileVM profile = await _profileService.GetProfile();
        return View(profile);
    }

    [HttpPost]
    public async Task<IActionResult> VehicleList(FilterVM filter)
    {
        VehiclePagination list = await _vehicleService.List(filter);
        return PartialView("_VehicleListPartial", list);
    }

    [HttpPost]
    public async Task<IActionResult> Update(ProfileVM profileVM)
    {
        if (!ModelState.IsValid)
        {
            return View("Index", profileVM);
        }

        await _userService.UpdateProfile(profileVM);

        TempData["NotificationMessage"] = NotificationMessages.Updated.Replace("{0}", "Profile");
        TempData["NotificationType"] = NotificationType.Success.ToString();

        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public async Task<IActionResult> VehicleModal(int vehicleId)
    {
        VehicleVM vehicleVM = await _vehicleService.Get(vehicleId);
        return PartialView("_VehiclePartial", vehicleVM);
    }

    [HttpPost]
    public async Task<IActionResult> SaveVehicle(VehicleVM vehicleVM)
    {
        if (!ModelState.IsValid)
        {
            VehicleVM updatedVehicleVM = await _vehicleService.Get(vehicleVM.Id);
            return PartialView("_VehiclePartial", updatedVehicleVM);
        }

        ResponseVM response = await _vehicleService.Save(vehicleVM);
        return Json(response);
    }

    public async Task<IActionResult> DeleteVehicle(int vehicleId)
    {
        await _vehicleService.Delete(vehicleId);
        return Json(new ResponseVM
        {
            Success = true,
            Message = NotificationMessages.Deleted.Replace("{0}", "Vehicle")
        });
    }


    /*---------------------------------------------------------------Change Password---------------------------------------------------------------------------------
    ----------------------------------------------------------------------------------------------------------------------------------------------------------*/
    [HttpGet]
    public IActionResult ChangePassword()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ChangePassword(ChangePasswordVM model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        ResponseVM response = await _userService.ChangePassword(model);

        TempData["NotificationMessage"] = response.Message;
        if (response.Success)
        {
            TempData["NotificationType"] = NotificationType.Success.ToString();
            return RedirectToAction("Logout", "Auth");
        }
        else
        {
            TempData["NotificationType"] = NotificationType.Error.ToString();
            return View(model);
        }
    }
}

MySociety.Web/Views/MyProfile/ChangePassword.cshtml
@using MySociety.Entity.ViewModels
@model ChangePasswordVM

@{
    ViewData["Title"] = "My Profile";
}


<!-- All form content: Note and form -->
<div class="change-content">
    <div class="mb-3">
        <h1 class="blue-text">Change Password</h1>
    </div>

    <div class="text-grey mb-2">
        <div class="fs-6">Enter a new password to update your account credentials.</div>
    </div>

    <!-- Form starts here-->
    <form asp-action="ChangePassword" asp-controller="MyProfile" id="ChangePasswordForm" class="changePassword-form"
        method="post">

        <!-- Current Password -->
        <div class="mb-3">
            <div class="form-floating input-group">
                <input asp-for="OldPassword" type="password" class="form-control" id="CurrentPassword" placeholder="">
                <label for="CurrentPassword">Current Password*</label>
                <span class="input-group-text">
                    <i class="eye-icon fa fa-eye-slash cursor-pointer"
                        onclick="togglePassword('CurrentPassword', this)"></i>
                </span>
            </div>
            <span asp-validation-for="OldPassword" class="text-danger"></span>
        </div>

        <!-- New Password -->
        <div class="mb-3">
            <div class="form-floating input-group">
                <input asp-for="NewPassword" type="password" class="form-control" id="NewPassword" placeholder="">
                <label asp-for="NewPassword">New Password*</label>
                <span class="input-group-text">
                    <i class="eye-icon fa fa-eye-slash cursor-pointer"
                        onclick="togglePassword('NewPassword', this)"></i>
                </span>
            </div>
            <span asp-validation-for="NewPassword" class="text-danger"></span>
        </div>

        <!-- Confirm Password -->
        <div class="mb-3">
            <div class="form-floating input-group">
                <input asp-for="ConfirmPassword" type="password" class="form-control" id="ConfirmPassword"
                    placeholder="">
                <label for="ConfirmPassword">Confirm New Password*</label>
                <span class="input-group-text">
                    <i class="eye-icon fa fa-eye-slash cursor-pointer"
                        onclick="togglePassword('ConfirmPassword', this)"></i>
                </span>
            </div>
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>

        <div class="d-flex gap-3">
            <button class="btn btn-custom" type="submit">
                Submit
            </button>
            <button type="reset" class="btn btn-custom-secondary">
                Cancel
            </button>
        </div>
    </form>
    <!-- Form ends here-->
</div>

MySociety.Web/Views/MyProfile/Index.cshtml
@using MySociety.Entity.ViewModels
@model ProfileVM
@{
    ViewData["Title"] = "My Profile";
}

<div class="container">
    <!-- User heading, search and add button -->
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div>
            <h1 class="blue-text mt-3 mb-0">My Profile</h1>
        </div>
        <div>
            <a asp-action="Index" asp-controller="Home" class="btn btn-custom">
                <img class="text-white" src="~/images/icons/chevron-left-white.svg" alt="">
                <span>Back</span>
            </a>
        </div>
    </div>

    <div class="row bg-custom p-3 mx-0">

        <!-- Photo and Name-->
        <div class="d-flex align-items-center pb-2">
            <div class="d-flex">
                <img id="img-preview" class="profile-img rounded-circle"
                    src="@(Model.ProfileImageUrl != null ? Model.ProfileImageUrl : "/images/profile.png")">
                <div class="camera-div bg-white">
                    <label for="profileImage">
                        <img class="camera-img" src="~/images/icons/camera.svg" alt="Upload Profile Image">
                    </label>
                </div>
            </div>
            <div>
                <div class="fs-3">@Model.Name</div>
                @if (User.IsInRole("Owner") || User.IsInRole("Tenant"))
                {
                    <div class="fw-semibold">
                        <span>House @Model.House,</span>
                        <span>@Model.Floor Floor,</span>
                        <span>@Model.Block Block</span>
                    </div>
                }
                <span asp-validation-for="Image" class="text-danger" id="imageValidationSpan"></span>
            </div>
        </div>

        <form asp-action="Update" asp-controller="MyProfile" class="" method="post" id="formMyProfile"
            enctype="multipart/form-data">

            <input asp-for="UserId" hidden>
            <input asp-for="Image" type="file" id="profileImage" class="d-none" onchange="imageValidation(this, 1)">

            <div class="mb-3">
                <div class="fs-4 pt-2"> Personal Information </div>

                <div class="row row-cols-2">

                    <div class="form-group col mt-2">
                        <label asp-for="Name">Name</label>
                        <input asp-for="Name" type="text" class="form-control" aria-describedby="Phone">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group col mt-2">
                        <label asp-for="Email">Email*</label>
                        <input asp-for="Email" type="email" class="form-control" aria-describedby="email" disabled>
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                            else.</small>
                    </div>

                    <div class="form-group col mt-2">
                        <label asp-for="Phone">Phone</label>
                        <input asp-for="Phone" type="text" class="form-control" aria-describedby="Phone">
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>

                </div>

                <div class="d-flex gap-3 mt-2 justify-content-end">
                    <button class="btn btn-custom" type="submit">
                        Update
                    </button>
                    @* <button class="btn btn-custom-secondary" type="reset">
                    Cancel
                </button> *@
                </div>
            </div>
        </form>


        <div>
            <div class="d-flex pt-2 justify-content-between align-items-center">
                <div class="fs-4"> Vehicle Information </div>
                <button class="btn btn-custom-secondary" onclick="getVehicle(0)">
                    + Add Vehicle
                </button>
            </div>

            <div class="pt-2">
                <div class="input-group w-25">
                    <input type="search" class="form-control" placeholder="Search" name="search" id="searchQuery"
                        oninput="paginationAjax(1)">
                    <button type="submit" class="input-group-text">
                        <img src="~/images/icons/search.svg" alt="">
                    </button>
                </div>
            </div>

            <div id="vehicleTable">
                <!-- Partial View of Vehicle List-->
            </div>

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="vehicleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog  modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content " id="vehicleContent">

        </div>
    </div>
</div>


@section Scripts {
    <script src="~/js/myProfile.js"></script>
}

MySociety.Web/Views/MyProfile/_VehicleListPartial.cshtml
@using MySociety.Entity.ViewModels
@model VehiclePagination

<!-- Table -->
<div class="table-responsive bg-white mt-3">
    <table class="table">
        <thead>
            <tr>
                <th scope="col" class="col-3 sortable-column" data-column="number" data-current-order="asc">
                    <span>Number</span>
                    <span class="" data-order="asc">
                        <img src="~/images/icons/arrow-up.svg" alt="">
                    </span>
                    <span class="d-none" data-order="desc">
                        <img src="~/images/icons/arrow-down.svg" alt="">
                    </span>
                </th>

                <th scope="col" class="col-3 sortable-column" data-column="name" data-current-order="desc">
                    <span>Name</span>
                    <span class="d-none" data-order="asc">
                        <img src="~/images/icons/arrow-up.svg" alt="">
                    </span>
                    <span class="d-none" data-order="desc">
                        <img src="~/images/icons/arrow-down.svg" alt="">
                    </span>
                </th>

                <th scope="col" class="col-2 sortable-column" data-column="type" data-current-order="desc">
                    <span>Type</span>
                    <span class="d-none" data-order="asc">
                        <img src="~/images/icons/arrow-up.svg" alt="">
                    </span>
                    <span class="d-none" data-order="desc">
                        <img src="~/images/icons/arrow-down.svg" alt="">
                    </span>
                </th>

                <th scope="col" class="col-2 sortable-column" data-column="parkingSlotNo" data-current-order="desc">
                    <span>Parking Slot No.</span>
                    <span class="d-none" data-order="asc">
                        <img src="~/images/icons/arrow-up.svg" alt="">
                    </span>
                    <span class="d-none" data-order="desc">
                        <img src="~/images/icons/arrow-down.svg" alt="">
                    </span>
                </th>

                <th scope="col" class="col-1">Action</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">

            @foreach (var vehicle in Model.Vehicles)
            {
                <tr>
                    <td>@vehicle.Number</td>
                    <td>@vehicle.Name</td>
                    <td>@vehicle.TypeName</td>
                    <td>@(vehicle.ParkingSlotNo == null ? "NA" : vehicle.ParkingSlotNo)</td>
                    <td>
                        <a type="button" class="ps-0 pe-3 btn" onclick="getVehicle(@vehicle.Id)">
                            <img src="/images/icons/edit.svg" alt="">
                        </a>

                        <a type="button" class="ps-0 btn btn-delete" onclick="deleteModal(this)" data-name="@vehicle.Name"
                            data-id="@vehicle.Id">
                            <img src="/images/icons/delete.svg" alt="">
                        </a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

@if (Model.Vehicles.Count > 0)
{
    <!-- Pagination Starts -->
    <div class="d-flex justify-content-end gap-1 flex-column flex-md-row pb-2">
        <div class="d-flex flex-row justify-content-end align-items-center mb-1 me-1 gap-1">
            <span>Items per page:</span>
            <select class="form-select w-auto" onchange="paginationAjax(1)" id="itemsPerPage"
                aria-label="Select items per page">
                <option value="5" selected="@(Model.Page.PageSize == 5 ? true : false)">5</option>
                <option value="10" selected="@(Model.Page.PageSize == 10 ? true : false)">10</option>
                <option value="15" selected="@(Model.Page.PageSize == 15 ? true : false)">15</option>
            </select>
        </div>

        <div class="d-flex flex-row justify-content-end align-items-center mb-1 gap-1">
            <span>Showing @Model.Page.FromRec - @Model.Page.ToRec of @Model.Page.TotalRecord</span>

            <!-- Previous Page Button -->
            <button class="btn bg-white border btn-prev @(Model.Page.CurrentPage > 1 ? "" : "disabled")"
                onclick="paginationAjax(@Model.Page.CurrentPage - 1)">
                <img src="~/images/icons/chevron-left.svg" alt="">
            </button>

            <!-- Next Page Button -->
            <button class="btn bg-white border btn-next @(Model.Page.CurrentPage < Model.Page.TotalPages ? "" : "disabled")"
                onclick="paginationAjax(@Model.Page.CurrentPage + 1)">
                <img src="~/images/icons/chevron-right.svg" alt="">
            </button>
        </div>
    </div>
    <!-- Pagination Ends -->
}
else
{
    <div class="text-center fs-5">No Record Found</div>
}

MySociety.Web/Views/MyProfile/_VehiclePartial.cshtml
@using MySociety.Entity.Models
@using MySociety.Entity.ViewModels
@model VehicleVM

<div class="modal-header">
    <h1 class="modal-title fs-5" id="staticBackdropLabel">Vehicle Details</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<form asp-action="SaveVehicle" asp-controller="MyProfile" id="SaveVehicleForm" method="post">
    <div class="modal-body">

        <input asp-for="Id" hidden>

        <div class="row row-cols-1">
            <div class="form-group col mb-3">
                <label asp-for="Number" class="fw-semibold">Number</label>
                <input asp-for="Number" type="text" class="form-control" aria-describedby="email">
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>

            <div class="form-group col mb-3">
                <label asp-for="Name" class="fw-semibold">Name</label>
                <input asp-for="Name" type="text" class="form-control" aria-describedby="Phone">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group col mb-3">
                <label asp-for="TypeId" class="fw-semibold">Vehicle Type</label>
                <select asp-for="TypeId" class="form-select" aria-label="vehicletype">
                    <option selected value="">Select Vehicle Type</option>
                    @foreach (VehicleType type in Model.Types)
                    {
                        <option value="@type.Id"> @type.Name</option>
                    }
                </select>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>

            <div class="form-group col mb-3">
                <label asp-for="ParkingSlotNo" class="fw-semibold">Parking slot number</label>
                <input asp-for="ParkingSlotNo" class="form-control" aria-describedby="ParkingSlotNumber">
                <span asp-validation-for="ParkingSlotNo" class="text-danger"></span>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-custom">Save</button>
        <button type="reset" class="btn btn-custom-secondary">Clear</button>
    </div>
</form>